SIM Application Toolkit: StkAgentService Class Reference
StkAgentService Class Reference
#include <stkagentservice.h>
Inherits QObject, and QDBusContext.
Public Slots
void Cancel ()
bool ConfirmCallSetup (const QString &info, uchar icon)
bool ConfirmLaunchBrowser (const QString &info, uchar icon, const QString &url)
void DisplayActionInformation (const QString &text, uchar icon)
void DisplayText (const QString &title, uchar icon, bool urgent)
void LoopTone (const QString &tone, const QString &text, uchar icon)
void PlayTone (const QString &tone, const QString &text, uchar icon)
void Release ()
bool RequestConfirmation (const QString &title, uchar icon)
QString RequestDigit (const QString &title, uchar icon)
QString RequestDigits (const QString &title, uchar icon, const QString &defaultValue, uchar minChars, uchar maxChars, bool hideTyping)
QString RequestInput (const QString &title, uchar icon, const QString &defaultValue, uchar minChars, uchar maxChars, bool hideTyping)
QString RequestKey (const QString &title, uchar icon)
uchar RequestSelection (const QString &title, uchar icon, OfonoMenuList items, short defaultValue)
Public Member Functions
StkAgentService (QObject *parent=0)
Detailed Description
Definition at line 22 of file stkagentservice.h.
Constructor & Destructor Documentation
StkAgentService::StkAgentService (QObject * parent = 0) [explicit]
Definition at line 34 of file stkagentservice.cpp.
                                                :
    QObject(parent)
{
}
Member Function Documentation
void StkAgentService::Cancel () [slot]
Definition at line 40 of file stkagentservice.cpp.
{
    // handle method call org.ofono.SimToolkitAgent.Cancel
qDebug() << "Cancel" ;
    closeLastWidget();
}
bool StkAgentService::ConfirmCallSetup (const QString & info, uchar icon) [slot]
Definition at line 48 of file stkagentservice.cpp.
References End, StkOfonoUtils::findIconUrl(), StkDialog::getAgentResponse(), No, STK_ERR_END, and Yes.
{
    // handle method call org.ofono.SimToolkitAgent.ConfirmCallSetup
    bool out0 = FALLBACK_BOOL;
qDebug() << "ConfirmCallSetup: " << info << "(" << icon << ")";
    closeLastWidget();
    StkDialog dlg(StkOfonoUtils::findIconUrl(icon),info,"qrc:/stkyesno.qml");
    dlg.exec();
    AgentResponse ret = dlg.getAgentResponse();
    switch (ret) {
    case Yes:
        out0 = true;
        break;
    case No:
        out0 = false;
        break;
    case End:
        connection().send(message().createErrorReply(STK_ERR_END,""));
        break;
    default:
        Q_ASSERT(false);
    }
    return out0;
}
bool StkAgentService::ConfirmLaunchBrowser (const QString & info, uchar icon, const QString & url) [slot]
Definition at line 74 of file stkagentservice.cpp.
References End, StkOfonoUtils::findIconUrl(), StkDialog::getAgentResponse(), No, STK_ERR_END, and Yes.
{
    // #### TODO #### launch browser with url parameter
    // handle method call org.ofono.SimToolkitAgent.ConfirmLaunchBrowser
    bool out0 = FALLBACK_BOOL;
qDebug() << "ConfirmLaunchBrowser: " << info << "(" << icon << ")" << " -- url: " << url;
    closeLastWidget();
    StkDialog dlg(StkOfonoUtils::findIconUrl(icon),info,"qrc:/stkyesno.qml");
    dlg.exec();
    AgentResponse ret = dlg.getAgentResponse();
    switch (ret) {
    case Yes:
        out0 = true;
        break;
    case No:
        out0 = false;
        break;
    case End:
        connection().send(message().createErrorReply(STK_ERR_END,""));
        break;
    default:
        Q_ASSERT(false);
    }
    return out0;
}
void StkAgentService::DisplayActionInformation (const QString & text, uchar icon) [slot]
Definition at line 101 of file stkagentservice.cpp.
References StkOfonoUtils::findIconUrl().
{
    // handle method call org.ofono.SimToolkitAgent.DisplayActionInformation
qDebug() << "DisplayActionInformation: " << text << "(" << icon << ")";
    closeLastWidget();
    StkDialog *dlg = new StkDialog(StkOfonoUtils::findIconUrl(icon),text,"qrc:/stkmessage.qml");
    widgetStack.append(dlg);
    dlg->show();
}
void StkAgentService::DisplayText (const QString & title, uchar icon, bool urgent) [slot]
Definition at line 112 of file stkagentservice.cpp.
References StkOfonoUtils::findIconUrl().
{
    // #### TODO #### blocking message dialog if urgent ?
    // handle method call org.ofono.SimToolkitAgent.DisplayText
qDebug() << "DisplayText: " << title << "(" << icon << ")" << " urgent: " << urgent;
    closeLastWidget();
    StkDialog *dlg = new StkDialog(StkOfonoUtils::findIconUrl(icon),title,"qrc:/stkmessage.qml");
    widgetStack.append(dlg);
    dlg->show();
}
void StkAgentService::LoopTone (const QString & tone, const QString & text, uchar icon) [slot]
Definition at line 124 of file stkagentservice.cpp.
References StkOfonoUtils::findIconUrl().
{
    // #### TODO #### loop playing tone
    // handle method call org.ofono.SimToolkitAgent.LoopTone
qDebug() << "LoopTone: " << tone << " : " << text << "(" << icon << ")";
    closeLastWidget();
    StkDialog *dlg = new StkDialog(StkOfonoUtils::findIconUrl(icon),text + "(playing: " + tone + ")","qrc:/stkmessage.qml");
    widgetStack.append(dlg);
    dlg->show();
}
void StkAgentService::PlayTone (const QString & tone, const QString & text, uchar icon) [slot]
Definition at line 136 of file stkagentservice.cpp.
References StkOfonoUtils::findIconUrl().
{
    // #### TODO #### play tone, block while playing
    // handle method call org.ofono.SimToolkitAgent.PlayTone
qDebug() << "PlayTone: " << tone << " : " << text << "(" << icon << ")";
    closeLastWidget();
    StkDialog dlg(StkOfonoUtils::findIconUrl(icon),text + "(playing: " + tone + ")","qrc:/stkpopup.qml");
    dlg.exec();
}
void StkAgentService::Release () [slot]
Definition at line 147 of file stkagentservice.cpp.
{
    // handle method call org.ofono.SimToolkitAgent.Release
qDebug() << "Release" ;
    while (closeLastWidget()) {}
    QApplication::instance()->exit();
}
bool StkAgentService::RequestConfirmation (const QString & title, uchar icon) [slot]
Definition at line 156 of file stkagentservice.cpp.
References Back, End, StkOfonoUtils::findIconUrl(), StkDialog::getAgentResponse(), No, STK_ERR_BACK, STK_ERR_END, and Yes.
{
    // handle method call org.ofono.SimToolkitAgent.RequestConfirmation
    bool out0 = FALLBACK_BOOL;
qDebug() << "RequestConfirmation: " << title << "(" << icon << ")";
    closeLastWidget();
    StkDialog dlg(StkOfonoUtils::findIconUrl(icon),title,"qrc:/stkpopup.qml");
    dlg.exec();
    AgentResponse ret = dlg.getAgentResponse();
    switch (ret) {
    case Yes:
        out0 = true;
        break;
    case No:
        out0 = false;
        break;
    case Back:
        connection().send(message().createErrorReply(STK_ERR_BACK,""));
        break;
    case End:
        connection().send(message().createErrorReply(STK_ERR_END,""));
        break;
    default:
        Q_ASSERT(false);
    }
    return out0;
}
QString StkAgentService::RequestDigit (const QString & title, uchar icon) [slot]
Definition at line 185 of file stkagentservice.cpp.
References Back, StkOfonoUtils::findIconUrl(), StkDialog::getAgentResponse(), StkDialog::getResponseData(), Ok, and STK_ERR_BACK.
{
    // handle method call org.ofono.SimToolkitAgent.RequestDigit
    QString out0 = FALLBACK_QSTRING;
qDebug() << "RequestDigit: " << title << "(" << icon << ")";
    closeLastWidget();
    /* #### TODO #### handle numeric and boundaries constraints
    StkDialog dlg(new StkInputKey(StkOfonoUtils::findIcon(icon),title));*/
    StkDialog dlg(StkOfonoUtils::findIconUrl(icon),title,"qrc:/stkinputkey.qml");
    dlg.exec();
    AgentResponse ret = dlg.getAgentResponse();
    switch (ret) {
    case Ok:
        out0 = dlg.getResponseData().toString();
        break;
    case Back:
        connection().send(message().createErrorReply(STK_ERR_BACK,""));
        break;
    default:
        Q_ASSERT(false);
    }
    return out0;
}
QString StkAgentService::RequestDigits (const QString & title, uchar icon, const QString & defaultValue, uchar minChars, uchar maxChars, bool hideTyping) [slot]
Definition at line 210 of file stkagentservice.cpp.
References Back, StkOfonoUtils::findIconUrl(), StkDialog::getAgentResponse(), StkDialog::getResponseData(), Ok, and STK_ERR_BACK.
{
    // handle method call org.ofono.SimToolkitAgent.RequestDigits
    QString out0 = defaultValue;
qDebug() << "RequestDigits: " << title << "(" << icon << ")" << " (" << defaultValue << ") [" << minChars << ".." << maxChars << "] passwd:" << hideTyping;
    closeLastWidget();
    /* #### TODO #### handle numeric and boundaries constraints
    StkInputText * inputText = new StkInputText(StkOfonoUtils::findIcon(icon),title);
    inputText->setDefaultText(defaultValue);
    inputText->setCharBounds(minChars,maxChars);
    inputText->setHideTyping(hideTyping);
    inputText->setNumeric(true);
    StkDialog dlg(inputText);*/
    StkDialog dlg(StkOfonoUtils::findIconUrl(icon),title,"qrc:/stkinputtext.qml",defaultValue);
    dlg.exec();
    AgentResponse ret = dlg.getAgentResponse();
    switch (ret) {
    case Ok:
        out0 = dlg.getResponseData().toString();
        break;
    case Back:
        connection().send(message().createErrorReply(STK_ERR_BACK,""));
        break;
    default:
        Q_ASSERT(false);
    }
    return out0;
}
QString StkAgentService::RequestInput (const QString & title, uchar icon, const QString & defaultValue, uchar minChars, uchar maxChars, bool hideTyping) [slot]
Definition at line 240 of file stkagentservice.cpp.
References Back, StkOfonoUtils::findIconUrl(), StkDialog::getAgentResponse(), StkDialog::getResponseData(), Ok, and STK_ERR_BACK.
{
    // handle method call org.ofono.SimToolkitAgent.RequestInput
    QString out0 = defaultValue;
qDebug() << "RequestInput: " << title << "(" << icon << ")" << " (" << defaultValue << ") [" << minChars << ".." << maxChars << "] passwd:" << hideTyping;
    closeLastWidget();
    /* #### TODO #### handle numeric and boundaries constraints
    StkInputText * inputText = new StkInputText(StkOfonoUtils::findIcon(icon),title);
    inputText->setDefaultText(defaultValue);
    inputText->setCharBounds(minChars,maxChars);
    inputText->setHideTyping(hideTyping);
    inputText->setNumeric(false);
    StkDialog dlg(inputText);*/
    StkDialog dlg(StkOfonoUtils::findIconUrl(icon),title,"qrc:/stkinputtext.qml",defaultValue);
    dlg.exec();
    AgentResponse ret = dlg.getAgentResponse();
    switch (ret) {
    case Ok:
        out0 = dlg.getResponseData().toString();
        break;
    case Back:
        connection().send(message().createErrorReply(STK_ERR_BACK,""));
        break;
    default:
        Q_ASSERT(false);
    }
    return out0;
}
QString StkAgentService::RequestKey (const QString & title, uchar icon) [slot]
Definition at line 270 of file stkagentservice.cpp.
References Back, StkOfonoUtils::findIconUrl(), StkDialog::getAgentResponse(), StkDialog::getResponseData(), Ok, and STK_ERR_BACK.
{
    // handle method call org.ofono.SimToolkitAgent.RequestKey
    QString out0 = FALLBACK_QSTRING;
qDebug() << "RequestKey: " << title << "(" << icon << ")";
    closeLastWidget();
    /* #### TODO #### handle numeric and boundaries constraints
    StkDialog dlg(new StkInputKey(StkOfonoUtils::findIcon(icon),title));*/
    StkDialog dlg(StkOfonoUtils::findIconUrl(icon),title,"qrc:/stkinputkey.qml");
    dlg.exec();
    AgentResponse ret = dlg.getAgentResponse();
    switch (ret) {
    case Ok:
        out0 = dlg.getResponseData().toString();
        break;
    case Back:
        connection().send(message().createErrorReply(STK_ERR_BACK,""));
        break;
    default:
        Q_ASSERT(false);
    }
    return out0;
}
uchar StkAgentService::RequestSelection (const QString & title, uchar icon, OfonoMenuList items, short defaultValue) [slot]
Definition at line 295 of file stkagentservice.cpp.
References Back, End, StkOfonoUtils::findIconUrl(), StkDialog::getAgentResponse(), StkDialog::getResponseData(), OfonoMenuEntry, Ok, STK_ERR_BACK, and STK_ERR_END.
{
    // handle method call org.ofono.SimToolkitAgent.RequestSelection
    uchar out0 = FALLBACK_UCHAR;
qDebug() << "RequestSelection: " << title << "(" << icon << ")" << " default: " << defaultValue;
    closeLastWidget();
     QList<StkMenuItem> dlgitems;
    foreach (const OfonoMenuEntry entry, items)
        dlgitems.append(StkMenuItem(StkOfonoUtils::findIconUrl(entry.icon), entry.label));
    StkDialog dlg(StkOfonoUtils::findIconUrl(icon),title,"qrc:/stkmenu.qml","",dlgitems,int(defaultValue));
    dlg.exec();
    AgentResponse ret = dlg.getAgentResponse();
    switch (ret) {
    case Ok:
        out0 = (uchar)dlg.getResponseData().toInt();
       break;
    case Back:
        connection().send(message().createErrorReply(STK_ERR_BACK,""));
        break;
    case End:
        connection().send(message().createErrorReply(STK_ERR_END,""));
        break;
    default:
        Q_ASSERT(false);
    }
    return out0;
}
The documentation for this class was generated from the following files:
src/stkagentservice.h
src/stkagentservice.cpp