SIM Application Toolkit: StkMainWindow Class Reference
StkMainWindow Class Reference
#include <stkmainwindow.h>
Inherits QMainWindow.
Public Member Functions
StkMainWindow (StkIf *stkIf, QWidget *parent=0)
~StkMainWindow ()
Detailed Description
Definition at line 21 of file stkmainwindow.h.
Constructor & Destructor Documentation
StkMainWindow::StkMainWindow (StkIf * stkIf, QWidget * parent = 0) [explicit]
Definition at line 17 of file stkmainwindow.cpp.
References StkOfonoProperties::mainMenuIconUrl(), StkOfonoProperties::mainMenuItems(), StkOfonoProperties::mainMenuTitle(), and StkMenuModel::setMenuItems().
                                                          :
    QMainWindow(parent)
{
    mStkIf = stkIf;
    // Store SimToolkit interface properties
    mStkProperties = new StkOfonoProperties(mStkIf);
    // Create a main menu as central widget
    this->mView = new QDeclarativeView;
    this->mView->setSource(QUrl("qrc:/stkmenu.qml"));
    this->mView->setResizeMode(QDeclarativeView::SizeRootObjectToView);
    this->setCentralWidget(this->mView);
    QObject *root = this->mView->rootObject();
    QObject *icon = root->findChild<QObject*>("icon");
    if (icon)
        icon->setProperty("source", mStkProperties->mainMenuIconUrl());
    QObject *title = root->findChild<QObject*>("title");
    if (title)
        title->setProperty("text", mStkProperties->mainMenuTitle());
    QDeclarativeContext *context = mView->rootContext();
    StkMenuModel * menuModel = new StkMenuModel();
    menuModel->setMenuItems(mStkProperties->mainMenuItems());
    context->setContextProperty("menuModel",menuModel);
    // connect signals
    connect(root, SIGNAL(itemSelected(int)), this, SLOT(responseOkWithSelection(int)));
    connect(root, SIGNAL(goBack()), this, SLOT(close()));
    connect(root, SIGNAL(endSession()), this, SLOT(close()));
}
StkMainWindow::~StkMainWindow ()
Definition at line 45 of file stkmainwindow.cpp.
{
    delete this->mView;
}
The documentation for this class was generated from the following files:
src/stkmainwindow.h
src/stkmainwindow.cpp