SIM Application Toolkit: StkOfonoUtils Class Reference
StkOfonoUtils Class Reference
#include <stkofonoutils.h>
Static Public Member Functions
static QPixmap findIcon (uchar id)
static QString findIconUrl (uchar id)
static QList< StkIf * > findSimToolkitInterfaces (const QDBusConnection &connection, MgrIf *mgrIf)
Detailed Description
Definition at line 21 of file stkofonoutils.h.
Member Function Documentation
QPixmap StkOfonoUtils::findIcon (uchar id) [static]
Definition at line 18 of file stkofonoutils.cpp.
{ // #### TODO implement
    return TEST_PIXMAP;
}
QString StkOfonoUtils::findIconUrl (uchar id) [static]
Definition at line 23 of file stkofonoutils.cpp.
Referenced by StkAgentService::ConfirmCallSetup(), StkAgentService::ConfirmLaunchBrowser(), StkAgentService::DisplayActionInformation(), StkAgentService::DisplayText(), StkAgentService::LoopTone(), StkOfonoProperties::mainMenuIconUrl(), StkOfonoProperties::mainMenuItems(), StkAgentService::PlayTone(), StkAgentService::RequestConfirmation(), StkAgentService::RequestDigit(), StkAgentService::RequestDigits(), StkAgentService::RequestInput(), StkAgentService::RequestKey(), and StkAgentService::RequestSelection().
{ // #### TODO implement
    return TEST_ICON_URL;
}
QList< StkIf * > StkOfonoUtils::findSimToolkitInterfaces (const QDBusConnection & connection, MgrIf * mgrIf) [static]
Definition at line 28 of file stkofonoutils.cpp.
References MgrIf::GetModems(), OfonoModem::objpath, and OfonoModem::varmap.
Referenced by main().
{
    QList<StkIf*> simToolkitInterfaces;
    QDBusError dbusError;
    // org.ofono.Manager interface GetModems method
    QDBusPendingReply<OfonoModemList> modemsCall = mgrIf->GetModems();
    modemsCall.waitForFinished();
    if (modemsCall.isError()) {
        dbusError = modemsCall.error();
        qDebug() << "Error:" << dbusError.name() << ":" << dbusError.message();
        return simToolkitInterfaces;
    }
    // loop foreach modem, find the first org.ofono.SimToolkit interface
    // in order to pass it to the SimToolkit main window
    foreach(const OfonoModem &pms, modemsCall.value()) {
        bool foundSimToolkit = false;
        // loop interfaces to find "org.ofono.SimToolkit"
        foreach(const QString &interface, pms.varmap.value("Interfaces").toStringList())
        {
            if (interface == "org.ofono.SimToolkit")
            {
                foundSimToolkit = true;
                break;
            }
        }
        if (foundSimToolkit)
        {
            // Instanciate proxy for org.ofono.SimToolkit interface
            simToolkitInterfaces.append(new StkIf("org.ofono",pms.objpath.path(),connection,NULL));
        }
    }
    return simToolkitInterfaces;
}
The documentation for this class was generated from the following files:
src/stkofonoutils.h
src/stkofonoutils.cpp