SIM Application Toolkit: StkDialog Class Reference
StkDialog Class Reference
#include <stkdialog.h>
Inherits QDialog.
Public Slots
void responseYes ()
void responseNo ()
void responseOkWithSelection (int selection)
void responseOkWithText (QString text)
void responseBack ()
void responseEnd ()
Public Member Functions
StkDialog (const QString &iconUrl, const QString &title, const QString &qmlViewUrl, const QString &defaultText="", const QList< StkMenuItem > &menuItems=QList< StkMenuItem >(), const int selection=-1, QWidget *parent=0)
AgentResponse getAgentResponse ()
QVariant getResponseData ()
Detailed Description
Definition at line 27 of file stkdialog.h.
Constructor & Destructor Documentation
StkDialog::StkDialog (const QString & iconUrl, const QString & title, const QString & qmlViewUrl, const QString & defaultText = "", const QList< StkMenuItem > & menuItems = QList<StkMenuItem>(), const int selection = -1, QWidget * parent = 0) [explicit]
Definition at line 18 of file stkdialog.cpp.
References responseBack(), responseEnd(), responseNo(), responseOkWithSelection(), responseOkWithText(), responseYes(), and StkMenuModel::setMenuItems().
                           :
    QDialog(parent)
{
    // Create QML View as central widget
    this->mView = new QDeclarativeView;
    this->mView->setSource(QUrl(qmlViewUrl));
    this->mView->setResizeMode(QDeclarativeView::SizeRootObjectToView);
    QVBoxLayout *layout = new QVBoxLayout;
    layout->addWidget(this->mView);
    setLayout(layout);
    // Find qml objects and connect signals
    QObject *object;
    QObject *root = this->mView->rootObject();
    // Main icon and title
    object = root->findChild<QObject*>("icon");
    if (object)
        object->setProperty("source", iconUrl);
    object = root->findChild<QObject*>("title");
    if (object)
        object->setProperty("text", title);
    // SIM Toolkit Menu
    QObject * menuView = root->findChild<QObject*>("menuView");
    if (menuView) {
        // set model "menuModel" for ListView "menuView"
        QDeclarativeContext *context = mView->rootContext();
        StkMenuModel * menuModel = new StkMenuModel();
        menuModel->setMenuItems(menuItems);
        context->setContextProperty("menuModel",menuModel);
        connect(root, SIGNAL(itemSelected(int)), this, SLOT(responseOkWithSelection(int)));
    }
    // Text edit / input
    QObject * editText = root->findChild<QObject*>("editText");
    if (editText) {
        editText->setProperty("text",defaultText);
        connect(root, SIGNAL(textEntered(QString)), this, SLOT(responseOkWithText(QString)));
    }
    // End button
    object = root->findChild<QObject*>("endRect");
    if (object)
        connect(root, SIGNAL(endSession()), this, SLOT(responseEnd()));
    // Back button
    object = root->findChild<QObject*>("backRect");
    if (object)
        connect(root, SIGNAL(goBack()), this, SLOT(responseBack()));
    // Yes button
    object = root->findChild<QObject*>("yesRect");
    if (object)
        connect(root, SIGNAL(accepted()), this, SLOT(responseYes()));
    // No button
    object = root->findChild<QObject*>("noRect");
    if (object)
        connect(root, SIGNAL(rejected()), this, SLOT(responseNo()));
    // Ok button
    object = root->findChild<QObject*>("okRect");
    if (object && !menuView && !editText)
        connect(root, SIGNAL(accepted()), this, SLOT(responseYes()));
    // default response: end session
    agentResponse = End;
}
Member Function Documentation
AgentResponse StkDialog::getAgentResponse () [inline]
Definition at line 36 of file stkdialog.h.
Referenced by StkAgentService::ConfirmCallSetup(), StkAgentService::ConfirmLaunchBrowser(), StkAgentService::RequestConfirmation(), StkAgentService::RequestDigit(), StkAgentService::RequestDigits(), StkAgentService::RequestInput(), StkAgentService::RequestKey(), and StkAgentService::RequestSelection().
    {
        return agentResponse;
    }
QVariant StkDialog::getResponseData () [inline]
Definition at line 41 of file stkdialog.h.
Referenced by StkAgentService::RequestDigit(), StkAgentService::RequestDigits(), StkAgentService::RequestInput(), StkAgentService::RequestKey(), and StkAgentService::RequestSelection().
    {
        return responseData;
    }
void StkDialog::responseBack () [inline, slot]
Definition at line 79 of file stkdialog.h.
Referenced by StkDialog().
    {
        agentResponse = Back;
        reject();
    }
void StkDialog::responseEnd () [inline, slot]
Definition at line 85 of file stkdialog.h.
Referenced by StkDialog().
    {
        agentResponse = End;
        reject();
    }
void StkDialog::responseNo () [inline, slot]
Definition at line 59 of file stkdialog.h.
Referenced by StkDialog().
    {
        agentResponse = No;
        reject();
    }
void StkDialog::responseOkWithSelection (int selection) [inline, slot]
Definition at line 65 of file stkdialog.h.
Referenced by StkDialog().
    {
        agentResponse = Ok;
        responseData = selection;
        accept();
    }
void StkDialog::responseOkWithText (QString text) [inline, slot]
Definition at line 72 of file stkdialog.h.
Referenced by StkDialog().
    {
        agentResponse = Ok;
        responseData = text;
        accept();
    }
void StkDialog::responseYes () [inline, slot]
Definition at line 53 of file stkdialog.h.
Referenced by StkDialog().
    {
        agentResponse = Yes;
        accept();
    }
The documentation for this class was generated from the following files:
src/stkdialog.h
src/stkdialog.cpp