SIM Application Toolkit: StkOfonoProperties Class Reference
StkOfonoProperties Class Reference
#include <stkofonoproperties.h>
Inherits QObject.
Public Member Functions
StkOfonoProperties (StkIf *stkIf, QObject *parent=0)
QList< StkMenuItem > mainMenuItems ()
QString mainMenuTitle ()
QString mainMenuIconUrl ()
Detailed Description
Definition at line 24 of file stkofonoproperties.h.
Constructor & Destructor Documentation
StkOfonoProperties::StkOfonoProperties (StkIf * stkIf, QObject * parent = 0) [explicit]
Definition at line 23 of file stkofonoproperties.cpp.
References StkIf::GetProperties().
                                                                    :
    QObject(parent)
{
    // org.ofono.SimToolkit interface GetProperties method
    QDBusPendingReply<QVariantMap> stkPropsCall = stkIf->GetProperties();
    stkPropsCall.waitForFinished();
    if (stkPropsCall.isError()) {
        QDBusError error = stkPropsCall.error();
        qDebug() << "Error:" << error.name() << ":" << error.message();
    }
    else
    {   // get properties map
        mProperties = stkPropsCall.value();
    }
}
Member Function Documentation
QString StkOfonoProperties::mainMenuIconUrl ()
Definition at line 61 of file stkofonoproperties.cpp.
References StkOfonoUtils::findIconUrl().
Referenced by StkMainWindow::StkMainWindow().
{
    return StkOfonoUtils::findIconUrl((uchar)mProperties.value("MainMenuIcon").toChar().toAscii());
}
QList< StkMenuItem > StkOfonoProperties::mainMenuItems ()
Definition at line 40 of file stkofonoproperties.cpp.
References StkOfonoUtils::findIconUrl(), and OfonoMenuEntry.
Referenced by StkMainWindow::StkMainWindow().
{
    QList<StkMenuItem> items;
    // "MainMenu" property
    QVariant varMenu = mProperties.value("MainMenu");
    QDBusArgument arg = varMenu.value<QDBusArgument>();
    // demarshall a(sy) QDBusArgument to a QList<OfonoMenuEntry> registered as OfonoMenuList
    OfonoMenuList menuList;
    arg >> menuList;
    foreach (const OfonoMenuEntry entry, menuList)
        items.append(StkMenuItem(StkOfonoUtils::findIconUrl(entry.icon), entry.label));
    return items;
}
QString StkOfonoProperties::mainMenuTitle ()
Definition at line 55 of file stkofonoproperties.cpp.
Referenced by StkMainWindow::StkMainWindow().
{
    return mProperties.value("MainMenuTitle").toString();
}
The documentation for this class was generated from the following files:
src/stkofonoproperties.h
src/stkofonoproperties.cpp