/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c MgrIf -p mgrif.h:mgrif.cpp -i ofonodbustypes.h ../interfaces/org.ofono.Manager.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * Do not edit! All changes made to it will be lost.
 */

#ifndef MGRIF_H_1299157943
#define MGRIF_H_1299157943

#include <QtCore/QObject>
#include <QtCore/QByteArray>
#include <QtCore/QList>
#include <QtCore/QMap>
#include <QtCore/QString>
#include <QtCore/QStringList>
#include <QtCore/QVariant>
#include <QtDBus/QtDBus>
#include "ofonodbustypes.h"

/*
 * Proxy class for interface org.ofono.Manager
 */
class MgrIf: public QDBusAbstractInterface
{
    Q_OBJECT
public:
    static inline const char *staticInterfaceName()
    { return "org.ofono.Manager"; }

public:
    MgrIf(const QString &service, const QString &path, const QDBusConnection &connection, QObject *parent = 0);

    ~MgrIf();

public Q_SLOTS: // METHODS
    inline QDBusPendingReply<OfonoModemList> GetModems()
    {
        QList<QVariant> argumentList;
        return asyncCallWithArgumentList(QLatin1String("GetModems"), argumentList);
    }

Q_SIGNALS: // SIGNALS
    void ModemAdded(const QDBusObjectPath &in0, const QVariantMap &in1);
    void ModemRemoved(const QDBusObjectPath &in0);
};

namespace org {
  namespace ofono {
    typedef ::MgrIf Manager;
  }
}
#endif
