/*
 * This file was generated by qdbusxml2cpp version 0.7
 * Command line was: qdbusxml2cpp -v -c StkAgentIfAdaptor -a stkagentifadaptor.h:stkagentifadaptor.cpp -i ofonodbustypes.h ../interfaces/org.ofono.SimToolkitAgent.xml
 *
 * qdbusxml2cpp is Copyright (C) 2010 Nokia Corporation and/or its subsidiary(-ies).
 *
 * This is an auto-generated file.
 * This file may have been hand-edited. Look for HAND-EDIT comments
 * before re-generating it.
 */

#ifndef STKAGENTIFADAPTOR_H_1300118444
#define STKAGENTIFADAPTOR_H_1300118444

#include <QtCore/QObject>
#include <QtDBus/QtDBus>
#include "ofonodbustypes.h"
class QByteArray;
template<class T> class QList;
template<class Key, class Value> class QMap;
class QString;
class QStringList;
class QVariant;

/*
 * Adaptor class for interface org.ofono.SimToolkitAgent
 */
class StkAgentIfAdaptor: public QDBusAbstractAdaptor
{
    Q_OBJECT
    Q_CLASSINFO("D-Bus Interface", "org.ofono.SimToolkitAgent")
    Q_CLASSINFO("D-Bus Introspection", ""
"  <interface name=\"org.ofono.SimToolkitAgent\">\n"
"    <method name=\"RequestSelection\">\n"
"      <annotation value=\"OfonoMenuList\" name=\"com.trolltech.QtDBus.QtTypeName.In2\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"title\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"icon\"/>\n"
"      <arg direction=\"in\" type=\"a(sy)\" name=\"items\"/>\n"
"      <arg direction=\"in\" type=\"n\" name=\"defaultValue\"/>\n"
"      <arg direction=\"out\" type=\"y\"/>\n"
"    </method>\n"
"    <method name=\"DisplayText\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"title\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"icon\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"urgent\"/>\n"
"    </method>\n"
"    <method name=\"RequestInput\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"title\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"icon\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"defaultValue\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"minChars\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"maxChars\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"hideTyping\"/>\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"RequestDigits\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"title\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"icon\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"defaultValue\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"minChars\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"maxChars\"/>\n"
"      <arg direction=\"in\" type=\"b\" name=\"hideTyping\"/>\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"RequestKey\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"title\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"icon\"/>\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"RequestDigit\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"title\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"icon\"/>\n"
"      <arg direction=\"out\" type=\"s\"/>\n"
"    </method>\n"
"    <method name=\"RequestConfirmation\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"title\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"icon\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"ConfirmCallSetup\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"info\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"icon\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"PlayTone\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"tone\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"text\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"icon\"/>\n"
"    </method>\n"
"    <method name=\"LoopTone\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"tone\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"text\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"icon\"/>\n"
"    </method>\n"
"    <method name=\"DisplayActionInformation\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"text\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"icon\"/>\n"
"    </method>\n"
"    <method name=\"ConfirmLaunchBrowser\">\n"
"      <arg direction=\"in\" type=\"s\" name=\"info\"/>\n"
"      <arg direction=\"in\" type=\"y\" name=\"icon\"/>\n"
"      <arg direction=\"in\" type=\"s\" name=\"url\"/>\n"
"      <arg direction=\"out\" type=\"b\"/>\n"
"    </method>\n"
"    <method name=\"Cancel\"/>\n"
"    <method name=\"Release\"/>\n"
"  </interface>\n"
        "")
public:
    StkAgentIfAdaptor(QObject *parent);
    virtual ~StkAgentIfAdaptor();

public: // PROPERTIES
public Q_SLOTS: // METHODS
    void Cancel();
    bool ConfirmCallSetup(const QString &info, uchar icon);
    bool ConfirmLaunchBrowser(const QString &info, uchar icon, const QString &url);
    void DisplayActionInformation(const QString &text, uchar icon);
    void DisplayText(const QString &title, uchar icon, bool urgent);
    void LoopTone(const QString &tone, const QString &text, uchar icon);
    void PlayTone(const QString &tone, const QString &text, uchar icon);
    void Release();
    bool RequestConfirmation(const QString &title, uchar icon);
    QString RequestDigit(const QString &title, uchar icon);
    QString RequestDigits(const QString &title, uchar icon, const QString &defaultValue, uchar minChars, uchar maxChars, bool hideTyping);
    QString RequestInput(const QString &title, uchar icon, const QString &defaultValue, uchar minChars, uchar maxChars, bool hideTyping);
    QString RequestKey(const QString &title, uchar icon);
    uchar RequestSelection(const QString &title, uchar icon, OfonoMenuList items, short defaultValue);
Q_SIGNALS: // SIGNALS
};

#endif
